### PR TITLE
improved test to use page object model

### PR DESCRIPTION
**Pull request by barranquerox**
I have added two classes and created a page object

### CODE REVIEW

**Review by mdampsmp75 — APPROVED** [review]

**Review by PereiraMV — APPROVED** [review]

**Comment by StephaneKEOU** [comment]
👍

**Comment by minatoYo** [comment]
je ne comprend pas

**Review by AndrewHat — CHANGES_REQUESTED** [review]
i don't understanad your code ! can you explain me ?

**Review by mdampsmp75 — APPROVED** [review]

**Review by StephaneKEOU — CHANGES_REQUESTED** [review]
I don't understand your code!

**Comment by barranquerox** [comment]
I explained it in the class! please pay attention!

**Comment by minatoYo** [comment]
comment approuvé

**Review by AndrewHat — APPROVED** [review]

**Review by StephaneKEOU — APPROVED** [review]

**Review by minatoYo — APPROVED** [review]

**Comment by ZahiaSA** [comment]
approuvé

**Comment by DialloS91** [comment]
Vous êtes trop forts

**Pull request merged**
